import type { ResumeTemplate } from '@/types'

export const resumeTemplates: ResumeTemplate[] = [
  {
    id: 'classic',
    name: '经典专业',
    description: '传统单栏布局，稳重大气，适合金融、法律、咨询等行业',
    category: '金融/财务',
    style: 'classic',
    primaryColor: '#1a365d',
    secondaryColor: '#2d3748',
    fontFamily: "'Noto Sans SC', 'Helvetica Neue', Arial, sans-serif",
  },
  {
    id: 'sidebar',
    name: '侧边栏布局',
    description: '左侧深色栏放个人信息和技能，右侧展示经历，清晰有层次',
    category: '营销/销售',
    style: 'sidebar',
    primaryColor: '#2b6cb0',
    secondaryColor: '#4a5568',
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
  },
  {
    id: 'banner',
    name: '渐变横幅',
    description: '顶部渐变色横幅突出姓名，正文双栏排列，现代感强',
    category: '互联网/科技',
    style: 'modern',
    primaryColor: '#0066ff',
    secondaryColor: '#00c6ff',
    fontFamily: "'Noto Sans SC', 'SF Pro Display', -apple-system, sans-serif",
  },
  {
    id: 'timeline',
    name: '时间轴',
    description: '左侧时间轴线串联经历节点，适合展示职业发展历程',
    category: '教育/服务',
    style: 'creative',
    primaryColor: '#e53e3e',
    secondaryColor: '#742a2a',
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
  },
  {
    id: 'cards',
    name: '卡片式',
    description: '每个板块用圆角卡片包裹，头像圆形首字母，风格年轻活泼',
    category: '设计/传媒',
    style: 'minimal',
    primaryColor: '#6b46c1',
    secondaryColor: '#553c9a',
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
  },
  {
    id: 'elegant',
    name: '优雅学术',
    description: '经典布局 + 衬线字体，沉稳优雅，适合科研、医疗、教育',
    category: '医疗/健康',
    style: 'classic',
    primaryColor: '#553c9a',
    secondaryColor: '#6b46c1',
    fontFamily: "'Noto Serif SC', Georgia, serif",
  },
  {
    id: 'tech-sidebar',
    name: '科技侧栏',
    description: '深色侧栏 + 等宽字体，程序员和大数据工程师首选',
    category: '互联网/科技',
    style: 'sidebar',
    primaryColor: '#1a202c',
    secondaryColor: '#2d3748',
    fontFamily: "'JetBrains Mono', 'Fira Code', Menlo, monospace",
  },
  {
    id: 'warm-banner',
    name: '温暖横幅',
    description: '暖色渐变横幅，亲和力强，适合医疗、健康、服务行业',
    category: '医疗/健康',
    style: 'modern',
    primaryColor: '#dd6b20',
    secondaryColor: '#ed8936',
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
  },
  {
    id: 'green-timeline',
    name: '环保时间轴',
    description: '绿色时间轴风格，稳重务实，适合建筑、制造、物流行业',
    category: '建筑/制造/物流',
    style: 'creative',
    primaryColor: '#276749',
    secondaryColor: '#22543d',
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
  },
  {
    id: 'graduate-cards',
    name: '应届生卡片',
    description: '卡片式布局突出项目和技能，适合高校应届毕业生',
    category: '高校',
    style: 'minimal',
    primaryColor: '#3182ce',
    secondaryColor: '#2b6cb0',
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
  },
]

export const getResumeTemplateById = (id: string): ResumeTemplate => {
  return resumeTemplates.find(t => t.id === id) || resumeTemplates[0]
}

export const templateCategories = [
  '全部',
  '互联网/科技',
  '金融/财务',
  '营销/销售',
  '设计/传媒',
  '教育/服务',
  '医疗/健康',
  '建筑/制造/物流',
  '高校',
]
